server:
  port: 9082
spring:
  application:
    name: dynamic-datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          driver-class-name: org.sqlite.JDBC
          #url: jdbc:sqlite::resource:db/tiku.db
          url: jdbc:sqlite:src/main/resources/db/tiku.db
          username:
          password:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/fund?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1234
  redis:
    host: 192.168.7.189
    port: 6379
    password: 572BEE5221B2206E37787829E03CCF9A
    database: 8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com:
      l: debug

#alipay:
#  gateway-url: https://openapi.alipay.com/gateway.do
#  app-id: 2021003116647251
#  #此处请填写你的应用私钥且转PKCS8格式
#  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrLyOBruPotpt3/4PfBdsramy+bjTtZyttldnYDt003ur5a9GxFzVthY8c2ORqmeOkEJXY1LZDkf8A/n51ZpFAl4sllE/8RAed2JxYHlK87A4TOW1adbLHJ7Q7IoeCjAdQ+rIHQL4tqCuL0c4ixHGAKocMMQCpj7WjrHBelJwYrwR5uqkzCXAKgBit2B1Ptw14ROvPxcw1bOKlj0yXYHVMNtv8+72v13F5qen049ibrU0O0DgxT4faMqZk74yY/KljjsM62TSqd0QTsDFqCe/tzcHekZUiACfh8k4PO80xAaN5bRf+MeVyqaztKdYsuNET5mQGe0p8g22AxlzXbkcZAgMBAAECggEAW6PkkiwZ/h6jo925rs7nwZo7lMZStzSf3w51jGCIsyETEWtS2kbeZz80mfDSdu7jGpV2Ypmc6RdjOBkFgbvizn1SFFANcbLJkQrAx7uT92c3Mbtwexi/GDZ9GZsmiBCGaieK3q8eIDsC9NrgS2R2jnI10aT6AcvZJUHO9hMAbYWADUr5JDx86M/RNGekRNPegPiPlLLp4S5YqI1wgy0g1itPKWfKZ6Cy8RsiyxZTK1Z5gpog66k+EvLUoGUaYr4/i210lBVlYSbGfXZ0RGRbiBL4TeDPLojHTL4xyHsOhm0l+cp/zwX+3nv+Yj1tgghFwD39L3G6dcYSDEl+hlUccQKBgQD8JMvJxR0lbJwgPrGjSIGLtzG8pEFUnO8JSsNUc3Apr8TM5mhPEA/sS4Y5s34Z3xh9c90ixUxoRa/QGtqAEPLatoxMGjl0+/qUetcPzTH59xU/G/W20qzQeJWX5dueMdkVlAxhSMUeGXJmEpKl+eGjFnZcHFCjEsvAkpWwGFLDVwKBgQCtzV28nW1+j3AGS+LYYvjj4AUkKEJtWa3oIaIT+vopFoFBdbvFI5DODBeTm1CRZZ72PbqFx3gBSFN/qvEKfUr3JWYrHO6aAvuJIHHL3pGA8xVSrs/XxtjUcB9mdho6uBcY83jAkBTadmlMD+M49Wr8E4i98bRurUgfrUgIe5mzDwKBgBVQdvmjdAdJ2xjOs+19n5XT8pxjtjIU4hADBegJqh2cAiLgB0lHrlDnQX13Mt21Ajj4pmTeEMtvuKD65CWXSTA75jg4r0q4UkJi7/MiAWuD+4PONUMzI/CrgNnKUHpa9GLilPlUUXVt6UG/qC3npa9HotG+gwKGADtTKNwt8jEZAoGAPdlpVCfJwVIWEYeL0GlYHO+ppLZW/Ub+pi7h2K5lu51wnfThv0Pq0ghnk3Wf9D3vlb1d1SGoyPwOCs6wPIVd2hmLBCilmFUbYi8Tj/NCYFsg6W2gNS9kFiVYZ0P8DY1ZWt25yPz9Dsk4q4Kz358mVVI2RTHwfbpYgj1N9wbVKW0CgYEAkzTd1ckuVBS8fJdk2vUp/WvzucF6vx8uKyA26+BcTQmdTOY+R3TFyQVCGhhpQwvZiE1pAwQG+8bn82wxL6AUBq0K4m8OnydlSglKSQw7sddkBcU27EGNtwrzgLKht0R0O6VHjrrYiRvhBa3UY978vkQ9+5DrDEjRbipj6BR3yjE=
#  #此处请填写你的应用公钥
#  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgf1nIA6kSrw4wQIyT6SF6HBNlfsFu0e+LwC8E2euW4vSGEeICOIrJ4v10E59y+loTHQpxDJfVvK7kkSer/rffop25N3ngmYFZYAlz0a0IHbQIrIo4YNJGOp/x9alVv1obzeUvHszL6vhZV0KeR2kmxsBaHOVRsPWxW8E1whI/6LRjHFiSKHbNuc2p2g5I2XvEmPsdmRojh2djyvoodQhEovBoCjrLjY7LXw2vBnxyZC1Wxxqj3o/6DpJSvvcQGrYicvi2etFM5MU4uhh2XFy6btG+X7SSrAj8rovXHrvASmtl5IPJ75r0Fs0nR4Iiamwhat8ZS8XyYjB1keGUIfCFwIDAQAB
#  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqy8jga7j6Labd/+D3wXbK2psvm407WcrbZXZ2A7dNN7q+WvRsRc1bYWPHNjkapnjpBCV2NS2Q5H/AP5+dWaRQJeLJZRP/EQHndicWB5SvOwOEzltWnWyxye0OyKHgowHUPqyB0C+Lagri9HOIsRxgCqHDDEAqY+1o6xwXpScGK8EebqpMwlwCoAYrdgdT7cNeETrz8XMNWzipY9Ml2B1TDbb/Pu9r9dxeanp9OPYm61NDtA4MU+H2jKmZO+MmPypY47DOtk0qndEE7Axagnv7c3B3pGVIgAn4fJODzvNMQGjeW0X/jHlcqms7SnWLLjRE+ZkBntKfINtgMZc125HGQIDAQAB
#  sign-type: RSA2
#  format: json
#  charset: UTF-8


alipay:
  gateway-url: https://openapi.alipay.com/gateway.do
  app-id: 2021003140624133
  #此处请填写你的应用私钥且转PKCS8格式
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCJ5Ks8MFD5YQoJtZK+yPfPmWUVOTjMIbLUcxJyEcPAZwKHcA+Nr53X5TYyC62ByUtQpy3qRr/IDiQ2OH8cidqFglxZEuNqSE+zo2+uadajhpHxHDNmPnvDCgCyRGoHl9uIgyvXyZKUpoZAtqxPhCFs3dOoLSTP6s8Ev0ZaLsqzEYdx+3VMzzrZyObP11PXKiB3wSBnun1Wza1pKRUaOQXtKei5SoCB1fbE2XpfrmKC8C1COK3QupSUJrCfWHgz9ZI5Slgewms1yDVJKmYU7RMAgHWg+Hg1SoBilRTYbYUp4mpaVVTNqwgF4Ek3OS/9uQiNSqEYSIXx8FvlHP3o/w8BAgMBAAECggEAWLCjEkthSYSImEYY5G0ONpBK26O6TFFAXDTHIGccqJuYnNQOrOrPcxUSDo5EQr3dmzpr5csrftjZoaYk244u5sA59XCYpLttx/TO2DdqvjLHm3Sv+oslvwSn/gDS0Z9yrBLyGBCmHsYcg3L60QoDFap3gCvJCZHVJRCBh2+hIBqnoKflBPi6OjMJqCqWyp93FeTUgWJeVPomvEebOUt3iAObUsLkgbHAjBRBQztLANEZ2PkJ7s0yhduuU2mGkwdEMnI7Aevz6MMopJOl8T3Hwy9AvwsnsA2xt721whAA9IVEuzHD7xxj5PMpbOGobrZwzXIm/SAsKmuB4Ns/v+O3IQKBgQDlfKvff/KlHsfP9kUppwwW6Awe8c7ndKnBHxskBZxsTKYTVTWu7puQrbB0SuefTfiBWIhhXHI29b/kbVnaGTfQ/Ny28nVWISpSeQWXICNv2MnICoTTgEDO1JM6cF2dkTXN4LtKNCQKUpjx2OnN7mrMc82+36i3Mk3tMStCyWLJCwKBgQCZ0wMTgu1miR97EEDKGgVxQpPCHYAdZNV7h9FCv4ujeAYSkhppFlLr0ABGtCjeV3BLaIeEbSVTvLrsXWIDO6WpLPBXcVklFdZJL33/RQd7NiZOE+0E41s10lKeTpFqs+SsBQ2JKT4w2nHdLJZ7FFEasoQYl+gYiPonG++W6GVHowKBgHuH5sUCjM0RiqGJgaVwRHO4KX4m0CeLhy1r3yI+2vr5L5TMk3889gSlWozfHVuFjzWhQJiYOOsY0ljV/D4IwSEAXJcmYL8iTzPh7X5yUGEOo1/JOcLYEQrFJxOYFOySlBHk3SyOcLAV0jqtdv3hTyALXj9XCezDaWs6wnzLByANAoGAEEvRlJyXR/iY9DGpm3+cOf6Cptr3OqX3E+o0miyuv3e0tPzzfVSXHlJf5R2rArsis2p0iOwDO1bQOsA95PfJuh1/rNPeTNZ+aCx23bdTbpMzBayIvK7Vd+M7S3gpYbODM1Ipt/E9nHFYBMV3f7yMRxbIdc6KESdZ0RDdlhAywp8CgYEAyerr+w5rqBe/y/+lHInxDd9A9mhHoHEpR/KOj+ImwaZhjAG0v614Q+dgKriV0A+4zGTkNoorEj2YVYTMKTKhIpfk0Unhd2Bl3BuaA5Mi2R41x0L5WAewnpjAAELkVR08WsYXdpCX7Jix25nn/X2lj5bt5ue1QAmaDTqOTHRoRdY=
  #此处请填写你的应用公钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzs2/Rnc6q6mWCZiUB80M3Jg0Wfg6zfLAavKcz2EFAouNXwnEZRExtYbQK+Cek+EyNfR99vRfpbhvnMlkJNtIieLGPHkwzjPHGOiC1PWxg7GP6M/AmPrBk3avw4In+DMO5ummUwIjjLFCvoIjuZ2BMN5KPf7Br32yp2vxAp1XFJ1oVSR7sIpbxLdwxYlwkPVxz9hwqRJ4vmNxCkLlcNn8M+TSoBw70sxec2ZAzuGd/OQYPAEkzlchkZalAsQYE9ACcDKk/GmZEf18Pvug6/Mg5YtV9kzYtnZ9cry0BgWw2cQa+880HOrVy1AqNa96wNrgsXbPOwNaEfb2xU2wnkndIwIDAQAB
  sign-type: RSA2
  format: json
  charset: UTF-8


