server:
  port: 9082
spring:
  application:
    name: dynamic-datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          driver-class-name: org.sqlite.JDBC
          #url: jdbc:sqlite::resource:db/tiku.db
          url: jdbc:sqlite:src/main/resources/db/tiku.db
          username:
          password:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/fund?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1234


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com:
      l: debug
# Sa-Token 配置
sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # 是否打开单点注销功能
    is-slo: true

    # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
    # 是否打开模式三
    isHttp: true
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
alipay:
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlRiJHMHap2nhtxNbDA7nf3cdWCaT5F5KxBHKHoPeQ05fxAGvgU+BDcBHMY9DwYiefMGWrHSmh+cwnCGyZfgHq4xqbs2XwK0O8Hxq2o3Q2uw3Fksj5x1bWJZ9mswxW7/+rmQr2aG19ekJvex4RkeqaRIgeqVP54BnJ36X1PTR48ABh9zJUGhBWd2iMKEbVQMWoL3wOHaRAPr3NSXaVk9V2NanU7QgzeHctxBq8xbmARMFN6lXLm4PKa7JPmUvdEJvULF5w1pvlWJN3i+6SS0x92GN2Nm/rbtq4AlQUxl5giG5osVwGBk4FGGNmlmhm6jgIoe6PWewcNmVUcYPrF72NQIDAQAB
  appid: 2021000119605754
  cancel_duration: 2000
  heartbeat_delay: 5
  heartbeat_duration: 900
  max_cancel_retry: 3
  max_query_retry: 5
  mcloud_api_domain: http://mcloudmonitor.com/gateway.do
  open_api_domain: https://openapi.alipay.com/gateway.do
  pid: 2088621957707518
  #此处请填写你的应用私钥且转PKCS8格式
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDa+DtszQpdtKJyFbcGarYhXidxs+QtIh6CEyBV7jqvtic6U5KASLjTBLlbtYX6QV2yI6k95SnqEY7nSO+AKr+T3AL6W63BuGuYVE96LprVZ+9jWjJkaYK9JzmKq05wXcUSJDGmeXa+SCbVsZs2PhpQiXpCm1oKnEMkPUDlyrgpS5KKHqAg/h6cDoqXojsLdn4/FdBnBIFTI6pE8ktBXjrSC1E2Io85BI2OUM7MVVh+B5spdThxJ/Tzkm29VERwwUp2Tm4aLZCGhuLAD0T/gUsDbd+cXMV7/wkcr4L6WhIxl+MzoWSRCWcQv3DZ7eLsDVif+TyWr/WhB9PkDDRFgmL/AgMBAAECggEABd0d4kT/YREERJ/WPeK/q9cUoVPa6WZ/gKY4eHSft7LeDA7O3oaUBHqc6BrNUq1LcAjKcHDhlXYQ6JqoZzs91BzRK5km5wgkQXkIg9IZrVtSKsvwi4XTzXLudIsv14x7SYgUmEuqZWATQie2a1ZwZ/W2g3AbkisrFR5azYyHL/vcayOdXn5g7UNIJ9jMULFyvD2/Y7DZhMUSChakP8hSX3FuAD1KubiPUkycRJ78UrV28HQpAvfkCyTve2n1mYxfYERrXfZ3uSYFV0OI8bu5EL7/RLpGn6nVONP1iRIOnG88FcEzG9CU775s4cbkSQiTXpsM4e+spjWn1mue0ojoQQKBgQDwWyDsUcAOjtwcjxr7WU7YpM6rPpBND7NFUEA44euonb5QOU2j+iPXPMVrdyLMCXXyQhoeffnWlMvjlGloS1J/Cwqw7RVIsx0mDGf16ICvwx558QZxKUZJK48RLF8IdHzfBcp7PaRW36vPoUQIzezorDL4dE75Eq8dLQYSjvH7oQKBgQDpOMJny8dDmHitd6/sL+2splCI3lFPmK+6tB9HQut5S4XT9l7qg6+xq9joVN5j8sbOshlkeF9rrPbgdpnmkyFZZusan1WXYWF/P9oKfgjN8fgqVzzARmbvG2b9+ve6wHum0xFHaLye8yzrcGseiocR/HciS27CObK1PsLZxvDanwKBgBdtioP+Y+4HVsUh3ctqJRlQ1yQx8PbR9PNooxnoS4Qf/BDtxPeaxiuQrN2Quz+QHIMElm8qcFPOJSGFsdCMpvnjJaOhOFXhv5GZ2/hINWLsbegM6kfVchhnuoY+APVeBV3nvpjMpVwiaSjP20XQbKsxPbah/6CfhZoebV0ZudSBAoGALMvGK4GsqIMkyszucYNTN5JKbb+mBo/hUQ8/4sQrzoR/FBOCb7ETkiDb7ORAQxpirVjwH6gvS9NRKBQfw3YHNdDa36YzHnyJ6ZMuIk3LCyOq8xcGiDf9lXfB9I67/pbyKTzpWLn5YN58hkx1hsw83WuMxn2OrKfAd6eybXoU0SkCgYB+jqw3qJLb9Yoa19GbImTHwklWNx29DK5PDEAs7WfjNdYYGIAc0kPpy/LD5ZpNXrhhxLNMQJz1Q5u1cw0/X7EgnqxSkOkASWtJ4nwQ+ONObOYYxw7CxcRiD3PIcZpBEC96w+d0VyPi1TipS9yTVRxq7owVWOU0WSGddTFoFT7i7g==
  #此处请填写你的应用公钥
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgcguLH9YSSCUjQoD4IpHjdPfavDNUi7e1a2TYAkTO8txDe0LDfGh4kfNenLRw9AY6QCWoS5MDTRCK0vEmOqFIAK1UqT08aRV3THLaSN1gND0iQdnuvwqVKCFs0zFFG3Q1W3oFX0MTSEUYv/0KID4Y7dhciwPeT5zhlbIyyoYMG9MpvqtZDZ1yF3DxJ47mnPcGPZrLZOcVv5R1wlq9EoGijPoRYPHXcduB8nKLaBb99sm2ja6NFNWPN79BiI5tVdowan0dz/c3l+k5jMFzPDB0XBGga2B8i1pFja4r55RrT/OJbLBs/2V7rbHXhA4Ys6QZRBE7gRBY/tSqVhodD7cpwIDAQAB
  query_duration: 5000
  sign_type: RSA2

