server:
  port: 9082
spring:
  application:
    name: dynamic-datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          driver-class-name: org.sqlite.JDBC
          #url: jdbc:sqlite::resource:db/tiku.db
          url: jdbc:sqlite:src/main/resources/db/tiku.db
          username:
          password:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/fund?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 1234


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com:
      l: debug
# Sa-Token 配置
sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # 是否打开单点注销功能
    is-slo: true

    # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
    # 是否打开模式三
    isHttp: true
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
alipay:
  gateway-url: https://openapi.alipay.com/gateway.do
  app-id: 2021003116647251
  #此处请填写你的应用私钥且转PKCS8格式
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrLyOBruPotpt3/4PfBdsramy+bjTtZyttldnYDt003ur5a9GxFzVthY8c2ORqmeOkEJXY1LZDkf8A/n51ZpFAl4sllE/8RAed2JxYHlK87A4TOW1adbLHJ7Q7IoeCjAdQ+rIHQL4tqCuL0c4ixHGAKocMMQCpj7WjrHBelJwYrwR5uqkzCXAKgBit2B1Ptw14ROvPxcw1bOKlj0yXYHVMNtv8+72v13F5qen049ibrU0O0DgxT4faMqZk74yY/KljjsM62TSqd0QTsDFqCe/tzcHekZUiACfh8k4PO80xAaN5bRf+MeVyqaztKdYsuNET5mQGe0p8g22AxlzXbkcZAgMBAAECggEAW6PkkiwZ/h6jo925rs7nwZo7lMZStzSf3w51jGCIsyETEWtS2kbeZz80mfDSdu7jGpV2Ypmc6RdjOBkFgbvizn1SFFANcbLJkQrAx7uT92c3Mbtwexi/GDZ9GZsmiBCGaieK3q8eIDsC9NrgS2R2jnI10aT6AcvZJUHO9hMAbYWADUr5JDx86M/RNGekRNPegPiPlLLp4S5YqI1wgy0g1itPKWfKZ6Cy8RsiyxZTK1Z5gpog66k+EvLUoGUaYr4/i210lBVlYSbGfXZ0RGRbiBL4TeDPLojHTL4xyHsOhm0l+cp/zwX+3nv+Yj1tgghFwD39L3G6dcYSDEl+hlUccQKBgQD8JMvJxR0lbJwgPrGjSIGLtzG8pEFUnO8JSsNUc3Apr8TM5mhPEA/sS4Y5s34Z3xh9c90ixUxoRa/QGtqAEPLatoxMGjl0+/qUetcPzTH59xU/G/W20qzQeJWX5dueMdkVlAxhSMUeGXJmEpKl+eGjFnZcHFCjEsvAkpWwGFLDVwKBgQCtzV28nW1+j3AGS+LYYvjj4AUkKEJtWa3oIaIT+vopFoFBdbvFI5DODBeTm1CRZZ72PbqFx3gBSFN/qvEKfUr3JWYrHO6aAvuJIHHL3pGA8xVSrs/XxtjUcB9mdho6uBcY83jAkBTadmlMD+M49Wr8E4i98bRurUgfrUgIe5mzDwKBgBVQdvmjdAdJ2xjOs+19n5XT8pxjtjIU4hADBegJqh2cAiLgB0lHrlDnQX13Mt21Ajj4pmTeEMtvuKD65CWXSTA75jg4r0q4UkJi7/MiAWuD+4PONUMzI/CrgNnKUHpa9GLilPlUUXVt6UG/qC3npa9HotG+gwKGADtTKNwt8jEZAoGAPdlpVCfJwVIWEYeL0GlYHO+ppLZW/Ub+pi7h2K5lu51wnfThv0Pq0ghnk3Wf9D3vlb1d1SGoyPwOCs6wPIVd2hmLBCilmFUbYi8Tj/NCYFsg6W2gNS9kFiVYZ0P8DY1ZWt25yPz9Dsk4q4Kz358mVVI2RTHwfbpYgj1N9wbVKW0CgYEAkzTd1ckuVBS8fJdk2vUp/WvzucF6vx8uKyA26+BcTQmdTOY+R3TFyQVCGhhpQwvZiE1pAwQG+8bn82wxL6AUBq0K4m8OnydlSglKSQw7sddkBcU27EGNtwrzgLKht0R0O6VHjrrYiRvhBa3UY978vkQ9+5DrDEjRbipj6BR3yjE=
  #此处请填写你的应用公钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgf1nIA6kSrw4wQIyT6SF6HBNlfsFu0e+LwC8E2euW4vSGEeICOIrJ4v10E59y+loTHQpxDJfVvK7kkSer/rffop25N3ngmYFZYAlz0a0IHbQIrIo4YNJGOp/x9alVv1obzeUvHszL6vhZV0KeR2kmxsBaHOVRsPWxW8E1whI/6LRjHFiSKHbNuc2p2g5I2XvEmPsdmRojh2djyvoodQhEovBoCjrLjY7LXw2vBnxyZC1Wxxqj3o/6DpJSvvcQGrYicvi2etFM5MU4uhh2XFy6btG+X7SSrAj8rovXHrvASmtl5IPJ75r0Fs0nR4Iiamwhat8ZS8XyYjB1keGUIfCFwIDAQAB
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqy8jga7j6Labd/+D3wXbK2psvm407WcrbZXZ2A7dNN7q+WvRsRc1bYWPHNjkapnjpBCV2NS2Q5H/AP5+dWaRQJeLJZRP/EQHndicWB5SvOwOEzltWnWyxye0OyKHgowHUPqyB0C+Lagri9HOIsRxgCqHDDEAqY+1o6xwXpScGK8EebqpMwlwCoAYrdgdT7cNeETrz8XMNWzipY9Ml2B1TDbb/Pu9r9dxeanp9OPYm61NDtA4MU+H2jKmZO+MmPypY47DOtk0qndEE7Axagnv7c3B3pGVIgAn4fJODzvNMQGjeW0X/jHlcqms7SnWLLjRE+ZkBntKfINtgMZc125HGQIDAQAB
  sign-type: RSA2
  format: json
  chatset: UTF-8


