spring:
  application:
    name: dynamic-datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite::resource:db/tiku.db
          username:
          password:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test
          username: root
          password: 1234
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com:
       l: debug